Component.arc = 8
Button.arc = 8
TextComponent.arc = 6
CheckBox.arc = 4
Component.focusWidth = 1
Component.innerFocusWidth = 0
Button.innerFocusWidth = 0
Button.margin = 3,12,3,12
Button.toolbar.margin = 3,8,3,8
Button.toolbar.spacingInsets = 1,2,1,2

ScrollBar.width = 10
ScrollBar.thumbArc = 999
ScrollBar.trackArc = 999
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.trackInsets = 2,2,2,2
ScrollBar.showButtons = false
ScrollPane.smoothScrolling = true

TabbedPane.tabHeight = 36
TabbedPane.tabInsets = 4,14,4,14
TabbedPane.tabAreaInsets = 0,6,0,6
TabbedPane.underlineHeight = 3
TabbedPane.tabSelectionHeight = 3
TabbedPane.showTabSeparators = false
TabbedPane.contentSeparatorHeight = 1
TabbedPane.textIconGap = 6

Table.rowHeight = 26
Table.showHorizontalLines = false
Table.showVerticalLines = false
Table.intercellSpacing = 0,0
Table.cellMargins = 2,8,2,8
TableHeader.height = 30
TableHeader.cellMargins = 2,8,2,8
TableHeader.showTrailingVerticalLine = false

TitlePane.unifiedBackground = true
PopupMenu.borderCornerRadius = 8
Popup.borderCornerRadius = 8
MenuItem.selectionInsets = 0,4,0,4
MenuItem.selectionArc = 6
ComboBox.selectionArc = 6
List.selectionArc = 6
ToolTip.borderCornerRadius = 6
SplitPaneDivider.style = plain
