package com.evefarm.service;

import com.evefarm.model.KillDayTypeRow;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.time.Day;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public final class KillsReportService {

    private static final float PAGE_WIDTH = PDRectangle.A4.getWidth();
    private static final float PAGE_HEIGHT = PDRectangle.A4.getHeight();
    private static final float MARGIN = 40f;
    private static final float CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
    private static final float HEADER_HEIGHT = 92f;
    private static final float ROW_HEIGHT = 18f;
    private static final float FOOTER_HEIGHT = 30f;

    private static final Color HEADER_BG = new Color(0x1a, 0x1a, 0x19);
    private static final Color HEADER_TEXT = Color.WHITE;
    private static final Color HEADER_SUBTEXT = new Color(0xc3, 0xc2, 0xb7);
    private static final Color ACCENT = new Color(0xe3, 0x49, 0x48);
    private static final Color TEXT_PRIMARY = new Color(0x0b, 0x0b, 0x0b);
    private static final Color TEXT_MUTED = new Color(0x89, 0x87, 0x81);
    private static final Color GRIDLINE = new Color(0xe1, 0xe0, 0xd9);
    private static final Color ROW_STRIPE = new Color(0xf5, 0xf6, 0xf8);
    private static final Color TABLE_HEADER_BG = new Color(0x3a, 0x3a, 0x38);

    public record ReportFilters(
            String characters,
            String faction,
            String system,
            LocalDate from,
            LocalDate to
    ) {
    }

    public void generateReport(Path outputFile, ReportFilters filters, List<KillDayTypeRow> rows) throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDFont regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            PDFont bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

            Report report = new Report(document, regular, bold);
            report.start(filters, rows);
            report.drawChart(rows);
            report.drawTable(rows);
            report.finish();

            document.save(outputFile.toFile());
        }
    }

    private static final class Report {
        private final PDDocument document;
        private final PDFont regular;
        private final PDFont bold;
        private PDPageContentStream stream;
        private float cursorY;
        private int pageNumber;

        Report(PDDocument document, PDFont regular, PDFont bold) {
            this.document = document;
            this.regular = regular;
            this.bold = bold;
        }

        void start(ReportFilters filters, List<KillDayTypeRow> rows) throws IOException {
            newPage();
            drawHeaderBand(filters);
            drawStatTiles(rows);
        }

        private void newPage() throws IOException {
            if (stream != null) {
                stream.close();
            }
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            stream = new PDPageContentStream(document, page);
            pageNumber++;
            cursorY = PAGE_HEIGHT - MARGIN;
            drawFooter();
        }

        private void drawFooter() throws IOException {
            stream.setNonStrokingColor(TEXT_MUTED);
            text(regular, 8, MARGIN, FOOTER_HEIGHT / 2, "Generated by EVE Farm");
            String pageLabel = "Page " + pageNumber;
            float width = regular.getStringWidth(pageLabel) / 1000 * 8;
            text(regular, 8, PAGE_WIDTH - MARGIN - width, FOOTER_HEIGHT / 2, pageLabel);
        }

        private boolean ensureSpace(float needed) throws IOException {
            if (cursorY - needed < FOOTER_HEIGHT + MARGIN) {
                newPage();
                return true;
            }
            return false;
        }

        private void drawHeaderBand(ReportFilters filters) throws IOException {
            stream.setNonStrokingColor(HEADER_BG);
            stream.addRect(0, PAGE_HEIGHT - HEADER_HEIGHT, PAGE_WIDTH, HEADER_HEIGHT);
            stream.fill();

            stream.setNonStrokingColor(ACCENT);
            stream.addRect(0, PAGE_HEIGHT - HEADER_HEIGHT, 6, HEADER_HEIGHT);
            stream.fill();

            stream.setNonStrokingColor(HEADER_TEXT);
            text(bold, 20, MARGIN, PAGE_HEIGHT - 36, "Kills Report");

            String subtitle = filters.characters() + "  ·  " + filters.faction()
                    + "  ·  " + filters.system()
                    + "  ·  " + filters.from() + " to " + filters.to();
            stream.setNonStrokingColor(HEADER_SUBTEXT);
            text(regular, 10, MARGIN, PAGE_HEIGHT - 54, subtitle);

            String generated = "Generated " + DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").format(LocalDateTime.now());
            stream.setNonStrokingColor(HEADER_SUBTEXT);
            text(regular, 9, MARGIN, PAGE_HEIGHT - 70, generated);

            cursorY = PAGE_HEIGHT - HEADER_HEIGHT - 24;
        }

        private void drawStatTiles(List<KillDayTypeRow> rows) throws IOException {
            int totalKills = rows.stream().mapToInt(KillDayTypeRow::count).sum();
            long distinctTypes = rows.stream().map(KillDayTypeRow::npcName).distinct().count();
            long distinctSystems = rows.stream().map(KillDayTypeRow::solarSystem).distinct().count();
            long distinctDays = rows.stream().map(KillDayTypeRow::date).distinct().count();

            String[] labels = {"Total Kills", "Ship Types", "Systems", "Active Days"};
            long[] values = {totalKills, distinctTypes, distinctSystems, distinctDays};

            float tileWidth = CONTENT_WIDTH / labels.length;
            float tileTop = cursorY;
            for (int i = 0; i < labels.length; i++) {
                float x = MARGIN + i * tileWidth;
                stream.setNonStrokingColor(TEXT_PRIMARY);
                text(bold, 22, x, tileTop - 22, String.valueOf(values[i]));
                stream.setNonStrokingColor(TEXT_MUTED);
                text(regular, 9, x, tileTop - 36, labels[i]);
            }
            cursorY = tileTop - 56;

            stream.setStrokingColor(GRIDLINE);
            stream.setLineWidth(0.75f);
            stream.moveTo(MARGIN, cursorY);
            stream.lineTo(PAGE_WIDTH - MARGIN, cursorY);
            stream.stroke();
            cursorY -= 20;
        }

        void drawChart(List<KillDayTypeRow> rows) throws IOException {
            Map<LocalDate, Integer> perDay = new TreeMap<>();
            for (KillDayTypeRow row : rows) {
                perDay.merge(row.date(), row.count(), Integer::sum);
            }
            if (perDay.isEmpty()) {
                return;
            }

            TimeSeries series = new TimeSeries("Kills");
            for (Map.Entry<LocalDate, Integer> entry : perDay.entrySet()) {
                LocalDate d = entry.getKey();
                series.addOrUpdate(new Day(d.getDayOfMonth(), d.getMonthValue(), d.getYear()), entry.getValue());
            }
            TimeSeriesCollection dataset = new TimeSeriesCollection(series);

            JFreeChart chart = ChartFactory.createTimeSeriesChart(null, "Date", "Kills", dataset, false, false, false);
            XYPlot plot = chart.getXYPlot();
            plot.setDomainAxis(new DateAxis("Date"));
            NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
            rangeAxis.setAutoRangeIncludesZero(true);
            rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

            chart.setBackgroundPaint(Color.WHITE);
            chart.setAntiAlias(true);
            chart.setTextAntiAlias(true);
            plot.setBackgroundPaint(Color.WHITE);
            plot.setOutlineVisible(false);
            plot.setDomainGridlinesVisible(false);
            plot.setRangeGridlinePaint(GRIDLINE);
            plot.getDomainAxis().setLabelPaint(TEXT_PRIMARY);
            plot.getDomainAxis().setTickLabelPaint(TEXT_PRIMARY);
            plot.getDomainAxis().setAxisLinePaint(TEXT_MUTED);
            plot.getDomainAxis().setTickMarkPaint(TEXT_MUTED);
            rangeAxis.setLabelPaint(TEXT_PRIMARY);
            rangeAxis.setTickLabelPaint(TEXT_PRIMARY);
            rangeAxis.setAxisLinePaint(TEXT_MUTED);
            rangeAxis.setTickMarkPaint(TEXT_MUTED);

            XYBarRenderer renderer = new XYBarRenderer();
            renderer.setShadowVisible(false);
            renderer.setDrawBarOutline(false);
            renderer.setBarPainter(new StandardXYBarPainter());
            renderer.setMargin(0.15);
            renderer.setSeriesPaint(0, ACCENT);
            plot.setRenderer(renderer);

            int chartWidthPx = 1000;
            int chartHeightPx = 380;
            BufferedImage chartImage = chart.createBufferedImage(chartWidthPx, chartHeightPx);

            float displayHeight = CONTENT_WIDTH * chartHeightPx / chartWidthPx;
            ensureSpace(displayHeight + 24);

            PDImageXObject pdImage = LosslessFactory.createFromImage(document, chartImage);
            stream.drawImage(pdImage, MARGIN, cursorY - displayHeight, CONTENT_WIDTH, displayHeight);
            cursorY -= displayHeight + 24;
        }

        void drawTable(List<KillDayTypeRow> rows) throws IOException {
            float[] columnWidths = {
                    CONTENT_WIDTH * 0.16f, CONTENT_WIDTH * 0.40f, CONTENT_WIDTH * 0.24f, CONTENT_WIDTH * 0.20f
            };
            String[] headers = {"Date", "Ship Type", "System", "Kills"};

            drawTableHeaderRow(columnWidths, headers);

            boolean stripe = false;
            for (KillDayTypeRow row : rows) {
                if (ensureSpace(ROW_HEIGHT)) {
                    drawTableHeaderRow(columnWidths, headers);
                }
                String[] values = {row.date().toString(), row.npcName(), row.solarSystem(), String.valueOf(row.count())};
                drawTableRow(columnWidths, values, stripe);
                stripe = !stripe;
            }
        }

        private void drawTableHeaderRow(float[] columnWidths, String[] headers) throws IOException {
            ensureSpace(ROW_HEIGHT);
            stream.setNonStrokingColor(TABLE_HEADER_BG);
            stream.addRect(MARGIN, cursorY - ROW_HEIGHT, CONTENT_WIDTH, ROW_HEIGHT);
            stream.fill();
            float x = MARGIN;
            for (int i = 0; i < headers.length; i++) {
                stream.setNonStrokingColor(Color.WHITE);
                text(bold, 9, x + 6, cursorY - ROW_HEIGHT + 5, headers[i]);
                x += columnWidths[i];
            }
            cursorY -= ROW_HEIGHT;
        }

        private void drawTableRow(float[] columnWidths, String[] values, boolean stripe) throws IOException {
            if (stripe) {
                stream.setNonStrokingColor(ROW_STRIPE);
                stream.addRect(MARGIN, cursorY - ROW_HEIGHT, CONTENT_WIDTH, ROW_HEIGHT);
                stream.fill();
            }
            float x = MARGIN;
            for (int i = 0; i < values.length; i++) {
                stream.setNonStrokingColor(TEXT_PRIMARY);
                text(regular, 9, x + 6, cursorY - ROW_HEIGHT + 5, truncate(values[i], columnWidths[i] - 10));
                x += columnWidths[i];
            }
            cursorY -= ROW_HEIGHT;
        }

        private String truncate(String value, float maxWidth) throws IOException {
            if (value == null) {
                return "";
            }
            if (regular.getStringWidth(value) / 1000 * 9 <= maxWidth) {
                return value;
            }
            String ellipsis = "...";
            StringBuilder sb = new StringBuilder(value);
            while (sb.length() > 1 && regular.getStringWidth(sb + ellipsis) / 1000 * 9 > maxWidth) {
                sb.setLength(sb.length() - 1);
            }
            return sb + ellipsis;
        }

        private void text(PDFont font, float size, float x, float y, String value) throws IOException {
            stream.beginText();
            stream.setFont(font, size);
            stream.newLineAtOffset(x, y);
            stream.showText(value);
            stream.endText();
        }

        void finish() throws IOException {
            if (stream != null) {
                stream.close();
            }
        }
    }
}
